pdf:
	pdflatex GraphBLAS_API_math.tex
	pdflatex GraphBLAS_API_math.tex
	pdflatex GraphBLAS_API_math.tex

clean:
	rm -f GraphBLAS_API_math.aux GraphBLAS_API_math.log GraphBLAS_API_math.out GraphBLAS_API_math.toc

cleanall: clean
	rm -f GraphBLAS_API_math.pdf
